Makefile: use LDLIBS to link libraries
The libraries must be added to the gcc "linker" execution after the object
files which reference symbols from the library. Otherwise the linker step
fails with:

    gcc -Wall -Werror -I/usr/include/json-c  -ljson-c  -luci -o poemgr pd69104.c poemgr.c uswflex.c
    /usr/bin/ld: /tmp/ccEERz2s.o: in function `uci_lookup_package':
    poemgr.c:(.text+0x2c): undefined reference to `uci_lookup_next'
    /usr/bin/ld: /tmp/ccEERz2s.o: in function `uci_lookup_section':
    poemgr.c:(.text+0x7b): undefined reference to `uci_lookup_next'
    /usr/bin/ld: /tmp/ccEERz2s.o: in function `uci_lookup_option':
    [...]
    collect2: error: ld returned 1 exit status
    make: *** [Makefile:12: poemgr] Error 1

The variable which is usually used in this position is called LDLIBS and
not LDFLAGS.

Signed-off-by: Sven Eckelmann <sven@narfation.org>